# This workflow will install the package development dependencies and run
# pre-commit with a single version of Python

name: Run pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "flit>=3.2,<4"
        flit install --deps=all
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --from-ref origin/main --to-ref origin/${GITHUB_HEAD_REF} --verbose
